Repository Barbebizarre/Project_Git, pull requests merged in 2023-07, with the labels that each got.

#6 Create PULL_REQUEST_TEMPLATE.md
  PULL_REQUEST_TEMPLATE.md
Labels: feature

#12 Update README.md
  README.md
Labels: enhancement

#13 Merge develop on main
  PULL_REQUEST_TEMPLATE.md
  README.md
Labels: enhancement, urgent

#14 Update .gitignore
  .gitignore
Labels: enhancement, feature

#15 Develop Close #11
  .gitignore
Labels: documentation, enhancement, feature

#18 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation

#20 Feature/#19 ajout du hooks close #19
  .eslintrc.json
  install-hooks.sh
Labels: bug, enhancement, feature, urgent

#22 Develop
  .eslintrc.json
  CODE_OF_CONDUCT.md
  install-hooks.sh
Labels: urgent

#24 Ajout fonction déchiffrement
  mess_crypt.js
  mess_uncrypt.js
Labels: feature

#26 ajout-du-script-de-génération-de-la-paire-de-clé-RSA Close #25
  encryption.js
Labels: enhancement, feature

#27 Develop
  encryption.js
  mess_crypt.js
  mess_uncrypt.js
Labels: feature, urgent

#32 Correction dans la fonction
  mess_crypt.js
Labels: bug, urgent
